microservice.name=guacamole-api
server.servlet.context-path=/guacamole-api/v1
server.port=8079

sandbox-service.uri=https://172.19.0.22/sandbox-service/api/v1
elasticsearch-service.uri=http://172.19.0.22/elastic/api/v1
user-and-group-service.uri=https://172.19.0.22/user-and-group/api/v1

# OpenID Connect OIDC
crczp.identity.providers[0].issuer=http://localhost:8080/dummy-issuer-server/
crczp.identity.providers[0].userInfoEndpoint=http://localhost:8080/dummy-issuer-server/userinfo

cors.allowed.origins=*